# Generated by Django 6.0.3 on 2026-06-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('summary', models.TextField()),
                ('vector', models.TextField()),
                ('mitigation', models.TextField()),
                ('cve', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'verbose_name_plural': 'attack info',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Breach',
            fields=[
                ('breach_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('breach_name', models.CharField(max_length=100)),
                ('breach_date', models.DateField()),
                ('data_exposed', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'breaches',
                'ordering': ['-breach_date'],
            },
        ),
        migrations.CreateModel(
            name='BreachSourceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80, unique=True)),
                ('count', models.PositiveIntegerField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='EmailCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_clean', models.BooleanField()),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('breach_count', models.PositiveSmallIntegerField(default=0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBreachStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Short month label, e.g. Jan', max_length=8, unique=True)),
                ('year', models.PositiveSmallIntegerField(default=2024)),
                ('breach_count', models.PositiveIntegerField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
